export const SET_BOOKS = "SET_BOOKS";
export const SET_FILTERED_BOOKS = "SET_FILTERED_BOOKS";
export const SET_KEYWORD_SEARCH = "SET_KEYWORD_SEARCH";
export const SET_APP_MESSAGE = "SET_APP_MESSAGE";
export const SET_IS_XHR_RUNNING = "SET_IS_XHR_RUNNING";

export const ADD_CART_ARTICLE = "ADD_CART_ARTICLE";
export const REMOVE_CART_ARTICLE = "REMOVE_CART_ARTICLE";

